import "./globals.css";
import "../style/index.scss";
import AppProvider from "@/lib/contextApi/AppProvider";
import ReduxProvider from "@/redux/provider";
import { DirectionProvider } from "@/hooks/useDirection";
import { Toaster } from "sonner";
import AuthWrapper from "@/components/auth/AuthWrapper";
import PermissionWrapper from "@/components/providers/PermissionWrapper";
import { ModaleProvider } from "@/context/ModaleContext";
import SmallModal from "@/components/elements/base-ui/modals/SmallModal";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <head>
          <meta httpEquiv="x-ua-compatible" content="ie=edge" />
          <meta name="description" content="Generated by create next app" />
          <meta name="robots" content="noindex, follow" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
          />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/icon?family=Material+Icons"
          />
        </head>

        <body suppressHydrationWarning={true} className="body-area">
          <ReduxProvider>
            <AppProvider>
              <ModaleProvider>
                <PermissionWrapper>
                  <DirectionProvider>
                    <AuthWrapper>{children}</AuthWrapper>
                  </DirectionProvider>
                </PermissionWrapper>
              </ModaleProvider>
              <Toaster position="top-center" richColors />
              <SmallModal />
            </AppProvider>
          </ReduxProvider>
        </body>
      </html>
    </>
  );
}
